BigOven ror app
ShinhyoBelok/BigOven pull request #23
Opened 2023-04-21 21:31 UTC by ShinhyoBelok

# App

We created a ruby on rails app that help you save your favorites recipes and let you keep track of your food inventory by adding the food in the app, When you want to cook a recipe you can generate a shopping list to see what you missing to be able to do that recipe.

## Features

- A login page.
- A registration page.
- A food list (with all CRUD implementation, except for 'update').
- A food detail page.
- A recipes list (with all CRUD implementation, except for 'update').
- A general shopping list view (all missing food for all your recipes and total price).
- A list of all public recipes from other users with their names and total prices.

2023-04-21 22:43 UTC, KDlamini requested changes
### Hi @ShinhyoBelok, @Gdiazdiaz 🙋‍♀️,  

Great work so far! 💯 
You have done a great job creating a working Recipe App using Rails and Devise authentication. 🎊 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞

✔️  Good PR title and description
✔️  Foods and recipes only appear to logged-in user
✔️  N+1 queries problem is fixed
✔️  Navigation menu that allows users to open all of the pages is well-implemented
✔️  The app schema looks similar to the [Entity Relationship Diagram](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_app_erd.png?raw=true)
✔️  Unit and integration specs are well-written

## Required Changes ♻️

**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 22:43 UTC, KDlamini commented on app/views/layouts/application.html.erb
> +        <span>BigOven</span>
[OPTIONAL] I think It would be best if you made the logo clickable because it is industry standard for a website logo to navigate to the home page.

2023-04-21 22:43 UTC, KDlamini commented on app/views/foods/_food.html.erb
> +  </td>
There seems to be a problem with the `destroy` action for foods. Attempting to delete any food item on the list throws an error.

![image](https://user-images.githubusercontent.com/38088818/233742211-f0bb1b38-e6cf-4c7e-8b47-723c8a92b2b0.png)

- Kindly look into it an ensure that food items can be deleted successfully.

2023-04-21 22:43 UTC, KDlamini commented on app/views/foods/shopping_list.html.erb
> +        <h3>Amount of food items to buy: <%= @shopping_list_foods.length %></h3>
The shopping list seem to be always empty even when there are ingredients in the recipe. Kindly look into it.

Recipe:

![image](https://user-images.githubusercontent.com/38088818/233742540-1a148c7f-ac7e-4d51-b425-22246594a3cd.png)

Shopping List:

![image](https://user-images.githubusercontent.com/38088818/233742670-a30ac3d0-a395-41a3-bf0f-6dc81749dca6.png)

2023-04-21 22:43 UTC, KDlamini commented on app/views/recipes/show.html.erb
> +  </table>
Only the owner of the recipe should be able to modify the recipe-foods/ingredients of the recipe. Currently, any user can delete ingredients for recipes they do not own.

- Kindly add authorisation for ingredients that allows only the recipe owner to modify ingredients.

2023-04-21 23:10 UTC, Gdiazdiaz commented on app/views/foods/shopping_list.html.erb
> +        <h3>Amount of food items to buy: <%= @shopping_list_foods.length %></h3>
Hi, @KDlamini, so the way we understood the shopping list, was that it was supposed to include everything you don't have, so if you have in your DB 1 Buffalo Mozzarela and 1 tomato (or mote), then the shopping list is saying that you don't need to buy more, so basically we handled what's on food, as ingredients that the user possess, if in recipe they add 10 tomatoes, when in food they said the hay 3, the the shopping list will say they need to buy 7, Can you confirm is this is not haw is supposed to behave?

2023-04-21 23:23 UTC, ShinhyoBelok commented on app/views/foods/shopping_list.html.erb
> +        <h3>Amount of food items to buy: <%= @shopping_list_foods.length %></h3>
@KDlamini that is probably because you have those quantities of that ingredient, because it only shows the missing food
"A general shopping list view (all missing food for all your recipes and total price)."

2023-04-22 00:25 UTC, mwanawabangona approved these changes
Hi @ShinhyoBelok 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 00:29 UTC, merged